### ISSUE TITLE
Anchors rules with transformed value and not discretized value

### ISSUE THREAD

**Issue by cjuers** [viadee/javaAnchorAdapters#20]
When running Anchors the rules it provides always contain the discretized value instead of the transformed value. For understandability we should use the transformed value instead. Example:
Instance:
Sex='male'
Survived='TRUE'
Rule:
IF Sex='male"
THEN PREDICT 1

Here TRUE is discretized with 1 but it should state TRUE in the Rule instead of 1.

**Comment by TobiasGoerke** [comment]
Are you referring to the result's predicted label? Is this an output formatting issue or rather the discretization itself?

**Comment by cjuers** [comment]
Output formatting. I think it is discretized correctly, but for easy of use should be formatted like the actual label and not like the discretized label

**Comment by TobiasGoerke** [comment]
I'm still considering the output formatting as WIP. I'll try and come up with a fix

**Comment by TobiasGoerke** [comment]
Closed by c3b4aed
