### ISSUE TITLE
Overview of tabular preprocessing

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/javaAnchorAdapters#22]
As more operations such as transformations and discretizations are being automized, it gets harder for the user to comprehend how the dataset is actually being preprocessed.
There should be some kind of overview (e.g. R summary style) after the preprocessing steps to facilitate data understanding.

**Comment by TobiasGoerke** [comment]
Closed by d49e1ce01aac60838b8408867ab799bc3892e340.
If in debug logging mode, an overview of how columns got discretized gets prettily logged

**Comment by fkoehne** [comment]
"Prettily logged" calls for an example in the README. ;)

**Comment by TobiasGoerke** [comment]
> 
> 
> "Prettily logged" calls for an example in the README. ;)

Done
