### ISSUE TITLE
Implement unsupervised & non-parameterized discretizer

### ISSUE THREAD

**Issue by MarvinBleier** [viadee/javaAnchorAdapters#29]
It would be a Nice-To-Have to add an unsupervised discretizer without any parameters or userinput because this would be easier to understand for the average user. If such a discretizer exists it should be called or implemented.

**Comment by MarvinBleier** [comment]
I was able to find four discretizers which could be used in this context: 
**U**nsupervised **C**orrelation **P**reserving **D**iscretization (UCPD), but this discretizer has two drawbacks: it is mulitvariate and thusly not easily implemented into the _column-based_ approach this implementation is using; and it needs normalized values to work without parameters. 

The **SOM**-Disc (https://pdfs.semanticscholar.org/6ee5/03fd5007b275310c241cc60f0d5e84bccc1b.pdf) uses _Self-Organized Maps_, they, like k-means, "partition the variability ranges of continuous features so as to preserve the distribution". But unlike k-means, only a maximum of partitions is needed apriori and this limit could be given with Instances/10 or something like this. The code would follow Self-Organized Maps.

**P**roportional k-**I**nterval **D**iscretizer (PKID) (http://users.monash.edu/~webb/Files/YangWebb03b.pdf) sets i_nterval size equal the number of intervals_. They should equal the Squareroot of the number of instances in the column. 
Another Discretizer from the same Paper ist Equal Size Discretizer (ESD), this discretizer builds all intervals with the same size, given as a parameter. In Garcias paper both PKID and ESD with size 30, rank highly in accuracy/kappa. 

Thusly i **would recommend PKID** as a unsupervised, non-parameterized discretizer. _But the ESD might be useful for @cjuers._ if used with "random" size-values in the autoAnchor approach.

**Comment by TobiasGoerke** [comment]
PKID sounds like an easy-to-implement solution that could be used as a default for "discretize=true". Lets give this a try. Might as well be a fairly low hanging fruit for your discretizer analysis.

**Comment by MarvinBleier** [comment]
Closed by #30
