### ISSUE TITLE
Invalid POM

### ISSUE THREAD

**Issue by KuzonFyre** [viadee/javaAnchorAdapters#40]
de.viadee.xai.anchor:DefaultConfigsAdapter has issues in it's pom which is eliminating transitive dependencies.

**Comment by TobiasGoerke** [comment]
Hey @KuzonFyre, I'm excited to see this research project being used. 
Can you point out the exact issue / help me with a reproducible example?

**Comment by KuzonFyre** [comment]
Thanks for the quick response. This is a great project and I hope it starts getting some more attention. This was just a warning I was getting when building from my pom. The project still works I just needed to manually add the dependencies that DefaultConfigsAdapter uses.

**Comment by KuzonFyre** [comment]
```[WARNING] The POM for de.viadee.xai.anchor:DefaultConfigsAdapter:jar:1.0.4 is invalid, transitive dependencies (if any) will not be available```

**Comment by TobiasGoerke** [comment]
I couldn't reproduce your warning but implemented maven's recommendations, so that a `mvn clean install` doesn't issue any more warnings. Does it work for you now?

**Comment by KuzonFyre** [comment]
Using 1.0.4
